// Class generated by AI.

package fr.piricraft.piricraftEssentials.managers;

import fr.piricraft.piricraftEssentials.PiricraftEssentials;
import fr.piricraft.piricraftEssentials.models.EssentialsProfile;
import fr.piricraft.piricraftEssentials.models.UserHome;
import fr.piricraft.piricraftEssentials.models.UserWarp;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

public class EssentialsDatabaseManager {

    private final PiricraftEssentials plugin;
    private Connection connection;
    private final Map<UUID, EssentialsProfile> profileCache = new ConcurrentHashMap<>();
    private final Map<String, UserWarp> warpCache = new ConcurrentHashMap<>();

    public EssentialsDatabaseManager(PiricraftEssentials plugin) {
        this.plugin = plugin;
    }

    public void initDatabase() {
        try {
            if (!plugin.getDataFolder().exists()) {
                plugin.getDataFolder().mkdirs();
            }

            File dbFile = new File(plugin.getDataFolder(), "essentials.db");
            this.connection = DriverManager.getConnection("jdbc:sqlite:" + dbFile.getAbsolutePath());

            try (Statement statement = connection.createStatement()) {
                statement.executeUpdate("CREATE TABLE IF NOT EXISTS piricraft_essentials_profiles (" +
                        "uuid VARCHAR(36) PRIMARY KEY, " +
                        "god_mode BOOLEAN DEFAULT FALSE, " +
                        "vanished BOOLEAN DEFAULT FALSE, " +
                        "social_spy BOOLEAN DEFAULT FALSE" +
                        ");");

                statement.executeUpdate("CREATE TABLE IF NOT EXISTS piricraft_homes (" +
                        "id INTEGER PRIMARY KEY AUTOINCREMENT, " +
                        "player_uuid VARCHAR(36) NOT NULL, " +
                        "name VARCHAR(32) NOT NULL, " +
                        "world VARCHAR(64) NOT NULL, " +
                        "x DOUBLE NOT NULL, " +
                        "y DOUBLE NOT NULL, " +
                        "z DOUBLE NOT NULL, " +
                        "yaw FLOAT NOT NULL, " +
                        "pitch FLOAT NOT NULL, " +
                        "created_at LONG NOT NULL, " +
                        "UNIQUE(player_uuid, name)" +
                        ");");

                statement.executeUpdate("CREATE TABLE IF NOT EXISTS piricraft_warps (" +
                        "name VARCHAR(32) PRIMARY KEY, " +
                        "owner_uuid VARCHAR(36) NOT NULL, " +
                        "world VARCHAR(64) NOT NULL, " +
                        "x DOUBLE NOT NULL, " +
                        "y DOUBLE NOT NULL, " +
                        "z DOUBLE NOT NULL, " +
                        "yaw FLOAT NOT NULL, " +
                        "pitch FLOAT NOT NULL, " +
                        "icon VARCHAR(64) NOT NULL, " +
                        "permission VARCHAR(128)" +
                        ");");
            }
        } catch (SQLException e) {
            plugin.getLogger().severe("Erreur lors de l'initialisation de la base de données SQLite : " + e.getMessage());
        }
    }

    public CompletableFuture<EssentialsProfile> loadProfileAsync(UUID uuid) {
        return CompletableFuture.supplyAsync(() -> {
            EssentialsProfile profile = new EssentialsProfile(uuid);

            String profileSql = "SELECT * FROM piricraft_essentials_profiles WHERE uuid = ?;";
            try (PreparedStatement stmt = connection.prepareStatement(profileSql)) {
                stmt.setString(1, uuid.toString());
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    profile.setGodMode(rs.getBoolean("god_mode"));
                    profile.setVanished(rs.getBoolean("vanished"));
                    profile.setSocialSpy(rs.getBoolean("social_spy"));
                }
            } catch (SQLException e) {
                plugin.getLogger().severe("Erreur lors du chargement du profil " + uuid + " : " + e.getMessage());
            }

            String homesSql = "SELECT * FROM piricraft_homes WHERE player_uuid = ?;";
            try (PreparedStatement stmt = connection.prepareStatement(homesSql)) {
                stmt.setString(1, uuid.toString());
                ResultSet rs = stmt.executeQuery();
                while (rs.next()) {
                    String name = rs.getString("name");
                    World world = Bukkit.getWorld(rs.getString("world"));
                    if (world != null) {
                        Location loc = new Location(
                                world,
                                rs.getDouble("x"),
                                rs.getDouble("y"),
                                rs.getDouble("z"),
                                rs.getFloat("yaw"),
                                rs.getFloat("pitch")
                        );
                        long createdAt = rs.getLong("created_at");
                        profile.addHome(new UserHome(name, loc, createdAt));
                    }
                }
            } catch (SQLException e) {
                plugin.getLogger().severe("Erreur lors du chargement des homes de " + uuid + " : " + e.getMessage());
            }

            profileCache.put(uuid, profile);
            return profile;
        });
    }

    public CompletableFuture<Void> saveProfileAsync(EssentialsProfile profile) {
        return CompletableFuture.runAsync(() -> {
            String profileSql = "INSERT INTO piricraft_essentials_profiles (uuid, god_mode, vanished, social_spy) " +
                    "VALUES (?, ?, ?, ?) " +
                    "ON CONFLICT(uuid) DO UPDATE SET " +
                    "god_mode = excluded.god_mode, " +
                    "vanished = excluded.vanished, " +
                    "social_spy = excluded.social_spy;";

            try (PreparedStatement stmt = connection.prepareStatement(profileSql)) {
                stmt.setString(1, profile.getPlayerUuid().toString());
                stmt.setBoolean(2, profile.isGodMode());
                stmt.setBoolean(3, profile.isVanished());
                stmt.setBoolean(4, profile.isSocialSpy());
                stmt.executeUpdate();
            } catch (SQLException e) {
                plugin.getLogger().severe("Erreur lors de la sauvegarde du profil " + profile.getPlayerUuid() + " : " + e.getMessage());
            }

            String deleteHomesSql = "DELETE FROM piricraft_homes WHERE player_uuid = ?;";
            try (PreparedStatement stmt = connection.prepareStatement(deleteHomesSql)) {
                stmt.setString(1, profile.getPlayerUuid().toString());
                stmt.executeUpdate();
            } catch (SQLException e) {
                plugin.getLogger().severe("Erreur lors du nettoyage des homes pour " + profile.getPlayerUuid() + " : " + e.getMessage());
            }

            String insertHomeSql = "INSERT INTO piricraft_homes (player_uuid, name, world, x, y, z, yaw, pitch, created_at) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);";
            try (PreparedStatement stmt = connection.prepareStatement(insertHomeSql)) {
                for (UserHome home : profile.getHomes().values()) {
                    Location loc = home.getLocation();
                    stmt.setString(1, profile.getPlayerUuid().toString());
                    stmt.setString(2, home.getName());
                    stmt.setString(3, loc.getWorld() != null ? loc.getWorld().getName() : "world");
                    stmt.setDouble(4, loc.getX());
                    stmt.setDouble(5, loc.getY());
                    stmt.setDouble(6, loc.getZ());
                    stmt.setFloat(7, loc.getYaw());
                    stmt.setFloat(8, loc.getPitch());
                    stmt.setLong(9, home.getCreatedAt());
                    stmt.addBatch();
                }
                stmt.executeBatch();
            } catch (SQLException e) {
                plugin.getLogger().severe("Erreur lors de l'insertion des homes pour " + profile.getPlayerUuid() + " : " + e.getMessage());
            }
        });
    }

    public void loadWarps() {
        warpCache.clear();
        String sql = "SELECT * FROM piricraft_warps;";
        try (Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                String name = rs.getString("name");
                UUID ownerUuid = UUID.fromString(rs.getString("owner_uuid"));
                World world = Bukkit.getWorld(rs.getString("world"));
                if (world == null) continue;

                Location loc = new Location(
                        world,
                        rs.getDouble("x"),
                        rs.getDouble("y"),
                        rs.getDouble("z"),
                        rs.getFloat("yaw"),
                        rs.getFloat("pitch")
                );

                Material icon = Material.matchMaterial(rs.getString("icon"));
                if (icon == null) icon = Material.ENDER_PEARL;

                String permission = rs.getString("permission");

                UserWarp warp = new UserWarp(name, ownerUuid, loc, icon, permission);
                warpCache.put(name.toLowerCase(), warp);
            }
        } catch (SQLException e) {
            plugin.getLogger().severe("Erreur lors du chargement des warps : " + e.getMessage());
        }
    }

    public long getWarpCountByPlayer(UUID playerUuid) {
        return warpCache.values().stream()
                .filter(warp -> warp.getOwnerUuid().equals(playerUuid))
                .count();
    }

    public void addWarp(UserWarp warp) {
        warpCache.put(warp.getName().toLowerCase(), warp);

        CompletableFuture.runAsync(() -> {
            String sql = "INSERT INTO piricraft_warps (name, owner_uuid, world, x, y, z, yaw, pitch, icon, permission) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) " +
                    "ON CONFLICT(name) DO UPDATE SET " +
                    "owner_uuid = excluded.owner_uuid, " +
                    "world = excluded.world, " +
                    "x = excluded.x, " +
                    "y = excluded.y, " +
                    "z = excluded.z, " +
                    "yaw = excluded.yaw, " +
                    "pitch = excluded.pitch, " +
                    "icon = excluded.icon, " +
                    "permission = excluded.permission;";

            try (PreparedStatement stmt = connection.prepareStatement(sql)) {
                Location loc = warp.getLocation();
                stmt.setString(1, warp.getName());
                stmt.setString(2, warp.getOwnerUuid().toString());
                stmt.setString(3, loc.getWorld() != null ? loc.getWorld().getName() : "world");
                stmt.setDouble(4, loc.getX());
                stmt.setDouble(5, loc.getY());
                stmt.setDouble(6, loc.getZ());
                stmt.setFloat(7, loc.getYaw());
                stmt.setFloat(8, loc.getPitch());
                stmt.setString(9, warp.getIcon().name());
                stmt.setString(10, warp.getPermission());
                stmt.executeUpdate();
            } catch (SQLException e) {
                plugin.getLogger().severe("Erreur lors de la sauvegarde du warp " + warp.getName() + " : " + e.getMessage());
            }
        });
    }

    public void removeWarp(String name) {
        warpCache.remove(name.toLowerCase());

        CompletableFuture.runAsync(() -> {
            String sql = "DELETE FROM piricraft_warps WHERE LOWER(name) = ?;";
            try (PreparedStatement stmt = connection.prepareStatement(sql)) {
                stmt.setString(1, name.toLowerCase());
                stmt.executeUpdate();
            } catch (SQLException e) {
                plugin.getLogger().severe("Erreur lors de la suppression du warp " + name + " : " + e.getMessage());
            }
        });
    }

    public EssentialsProfile getProfileFromCache(UUID uuid) {
        return profileCache.get(uuid);
    }

    public Map<String, UserWarp> getWarpCache() {
        return warpCache;
    }

    public void unloadProfile(UUID uuid) {
        EssentialsProfile profile = profileCache.get(uuid);
        if (profile != null) {
            saveProfileAsync(profile).thenRun(() -> profileCache.remove(uuid));
        }
    }

    public void closeConnection() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
            }
        } catch (SQLException e) {
            plugin.getLogger().severe("Erreur lors de la fermeture de la connexion BDD : " + e.getMessage());
        }
    }
}